### ISSUE TITLE
Serial enhancements required

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/DxCore#113]
1. We need the capability to support a larger number of pin mapping options. Currently it's only 2, we need to support up to 7 including none, and we need to do it in a vaguely efficient manner, not like it's done now.  Required for DD support
 
2. We need the ability for a serial port to start by default in a given swap state (for example, Serial0 on a DB or DD that is using a crystal, or anything using external clock. Maybe it should ALWAYS default that, on the assumption that nobody would make a breakout board for the Dx-series parts that connected PA0 and PA1 to serial adapter after the release of the DB and hence the surprise location of the crystal pins at PA0/PA1. (I was expecting to find them in PORTF, personally)) 

3. And if we could shrink the size of the binaries it generates that'd be awesome too. print and the ISRs are fat and slow, The megaTinyCore people on 2k and 4k parts are complaining about the size, and it's only a miracle people aren't complaining about the speed too.

**Comment by MX682X** [comment]
Well, there we go, removed the trailing whitespaces that caused some errors in the checks. Also finished the pinmux none option. Right now, it can be only enabled with the swap function, not with pins. Also, if the none option is available, the swap function accepts any negative value to enable the pinmux none, because that's smaller.

**Comment by SpenceKonde** [comment]
This is checked in now. Huzzah!  Plus loopback/opendrain/RS485 mode and the cleanup of the variants that this permitted. Event and RX only, TX only modes untested. The RX/TX only i'm confident in. I have no idea what I'll find with the event stuff. The documentation for some features borders on useless.
