### ISSUE TITLE
Bug in Arduino.h

### ISSUE THREAD

**Issue by dpetican** [SpenceKonde/DxCore#145]
There is a bug in either the documentation or Arduino.h  The constant is PIN_INLVL_SCHMITT in the docs and in the header:

`#define PIN_INLVL_SCHMIT     0x2000 // MVIO parts only`

**Comment by SpenceKonde** [comment]
Thanks. The documented spelling is the intended one, will correct.

**Comment by SpenceKonde** [comment]
Fixed
