### ISSUE TITLE
DxCore.h doesn't compile

### ISSUE THREAD

**Issue by mrWheel** [SpenceKonde/DxCore#146]
@SpenceKonde 

Due to the Wire / I2C problem I try to make the switch to an AVR128DB28.

First try:
```
In file included from /Users/me/Documents/ArduinoProjects/MySketches/Blink/Blink.ino:31:0:
/Users/me/Library/Arduino15/packages/DxCore/hardware/megaavr/1.3.6/libraries/DxCore/src/DxCore.h: In function 'bool setTCA0MuxByPort(uint8_t)':
/Users/me/Library/Arduino15/packages/DxCore/hardware/megaavr/1.3.6/libraries/DxCore/src/DxCore.h:88:24: error: 'digitalPortToPinZero' was not declared in this scope
     uint8_t base_pin = digitalPortToPinZero(port);
                        ^~~~~~~~~~~~~~~~~~~~

Error compiling for board AVR DB-series (no bootloader).
```
Is this expected behaviour?

**Comment by mrWheel** [comment]
It must be me! Suddenly it compiles and PA7 blinks....

**Comment by SpenceKonde** [comment]
DxCore.h is the problem....

**Comment by SpenceKonde** [comment]
I named that macro something different in every damned file

**Comment by mrWheel** [comment]
> I named that macro something different in every damned file

Ha ha!

But the funny thing is: I have not included `DxCore.h` (or is it includes by the core somehow?)

**Comment by mrWheel** [comment]
> Weird.... I cannot explain why it would have been compiling that library

Well, you know me by now!
