### ISSUE TITLE
Hardware flow control

### ISSUE THREAD

**Issue by mrWheel** [SpenceKonde/DxCore#157]
In the readme you mention XCK and XDIR.
Are these pins used for a hardware flow control setup?

In the microchip online documentation there is an example of flow control for not sending data when the receiving parts is not ready, but I need the opposite..

i communicate with a GSM modem over USART but mis characters if the modem sends a lot of chars in a burst. The modem has DTR and CTS lines.

How do I code this for an AVR-DB processor?

**Comment by MX682X** [comment]
the USART module on the AVR-Dx parts does not support hardware flow control (CTS/RTS), at least I haven't seen any part that does it, yet.
The pin XCK is used to receive/transmit a clock in the synchronous operation mode.
the pin XDIR is used in the RS485 mode to enable the transceiver.  


A way to handle the bursts would be to increase the SERIAL_RX_BUFFER_SIZE in UART.h to an apropriate size and/or reduce the baudrate, so the time between interrupts is increased
