### ISSUE TITLE
Sleep mode(s) not fully supported

### ISSUE THREAD

**Issue by nabelekt** [SpenceKonde/DxCore#161]
I am working to be able to put a DA-series module into sleep mode. If I copy the example from [PowerSave.md](https://github.com/SpenceKonde/DxCore/blob/master/megaavr/extras/PowerSave.md) and attempt to build, I get `'RTC_CLKSEL_INT32K_gc' was not declared in this scope`.

It looks like `PowerSave.md` was changed from the megaTinyCore version, so I assume there is some support, but perhaps it is incomplete? I can build the same sketch fine with a megaTinyCore board selected. If I [search for `RTC_CLKSEL_INT32K_gc` in the megaTinyCore repo](https://github.com/SpenceKonde/megaTinyCore/search?q=RTC_CLKSEL_INT32K_gc), I can see that it is defined in the ioheader files. Those files don't exist for DxCore?

**Comment by nabelekt** [comment]
Thanks for the reply! And glad to hear that the 1.3.7 release is near; looking forward to it.

**Comment by SpenceKonde** [comment]
This workaround is in the 1.3.9 release (it's in 1.3.8 too but that release is busted) 1.3.9 will be out today, have had a lot going on this week.
