### ISSUE TITLE
Wire.swap(2) does not work on AVR128DB28

### ISSUE THREAD

**Issue by dpetican** [SpenceKonde/DxCore#164]
It was working before.  When was before?  Not sure, but in 1.3.6 `Wire.swap(2)` does not work.  However, `Wire.pins(PIN_PC2, PIN_PC3)` does work.  If its relevant I am now using 3.3V for VDDIO2 but before it was 5V.  Thanks.

**Comment by SpenceKonde** [comment]
Oh what the fuck happened to this.....

**Comment by SpenceKonde** [comment]
Okay, this is fixed!
