### ISSUE TITLE
Does not compile for AVR128DA28

### ISSUE THREAD

**Issue by pfoun** [SpenceKonde/DxCore#165]
First, thank you for your work on these cores.  I have benefited from them immensely and follow your ongoing development.  Keep up the good work!

I would like to report that the core will not compile for AVR128DA28 or any other DA series that I tried.  DxCore was upgraded from boards manager to 1.3.8.  This example is from a Linux computer, Windows computer throws the same error.  Here is the code and the error follows.

`void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}`

Arduino: 1.8.13 (Linux), Board: "AVR DA-series (no bootloader), AVR128DA28, 24 MHz internal, 1.9V, Disabled/Disabled, EEPROM retained, Hardware Reset (recommended), TCB2 (recommended), Default, 1.5k flash, no floats, On all pins, like usual, 8ms, Disabled"

/home/owner/arduino-1.8.13/arduino-builder -dump-prefs -logger=machine -hardware /home/owner/arduino-1.8.13/hardware -hardware /home/owner/.arduino15/packages -hardware /home/owner/Arduino/hardware -tools /home/owner/arduino-1.8.13/tools-builder -tools /home/owner/arduino-1.8.13/hardware/tools/avr -tools /home/owner/.arduino15/packages -built-in-libraries /home/owner/arduino-1.8.13/libraries -libraries /home/owner/Arduino/libraries -fqbn=DxCore:megaavr:avrda:chip=128DA28,clock=24internal,bodvoltage=1v9,bodmode=disabled,eesave=enable,resetpin=reset,millis=tcb2,printf=default,attach=allenabled,startuptime=8,appspm=no -ide-version=10813 -build-path /tmp/arduino_build_380230 -warnings=all -build-cache /tmp/arduino_cache_821657 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/home/owner/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino18 -prefs=runtime.tools.avrdude-6.3.0-arduino18.path=/home/owner/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino18 -prefs=runtime.tools.arduinoOTA.path=/home/owner/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/owner/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.python3.path=/home/owner/.arduino15/packages/megaTinyCore/tools/python3/3.7.2-post1 -prefs=runtime.tools.python3-3.7.2-post1.path=/home/owner/.arduino15/packages/megaTinyCore/tools/python3/3.7.2-post1 -prefs=runtime.tools.avr-gcc.path=/home/owner/.arduino15/packages/DxCore/tools/avr-gcc/7.3.0-atmel3.6.1-azduino4b -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-azduino4b.path=/home/owner/.arduino15/packages/DxCore/tools/avr-gcc/7.3.0-atmel3.6.1-azduino4b -verbose /tmp/untitled1666926883.tmp/sketch_nov01a/sketch_nov01a.ino
/home/owner/arduino-1.8.13/arduino-builder -compile -logger=machine -hardware /home/owner/arduino-1.8.13/hardware -hardware /home/owner/.arduino15/packages -hardware /home/owner/Arduino/hardware -tools /home/owner/arduino-1.8.13/tools-builder -tools /home/owner/arduino-1.8.13/hardware/tools/avr -tools /home/owner/.arduino15/packages -built-in-libraries /home/owner/arduino-1.8.13/libraries -libraries /home/owner/Arduino/libraries -fqbn=DxCore:megaavr:avrda:chip=128DA28,clock=24internal,bodvoltage=1v9,bodmode=disabled,eesave=enable,resetpin=reset,millis=tcb2,printf=default,attach=allenabled,startuptime=8,appspm=no -ide-version=10813 -build-path /tmp/arduino_build_380230 -warnings=all -build-cache /tmp/arduino_cache_821657 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/home/owner/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino18 -prefs=runtime.tools.avrdude-6.3.0-arduino18.path=/home/owner/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino18 -prefs=runtime.tools.arduinoOTA.path=/home/owner/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/owner/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.python3.path=/home/owner/.arduino15/packages/megaTinyCore/tools/python3/3.7.2-post1 -prefs=runtime.tools.python3-3.7.2-post1.path=/home/owner/.arduino15/packages/megaTinyCore/tools/python3/3.7.2-post1 -prefs=runtime.tools.avr-gcc.path=/home/owner/.arduino15/packages/DxCore/tools/avr-gcc/7.3.0-atmel3.6.1-azduino4b -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-azduino4b.path=/home/owner/.arduino15/packages/DxCore/tools/avr-gcc/7.3.0-atmel3.6.1-azduino4b -verbose /tmp/untitled1666926883.tmp/sketch_nov01a/sketch_nov01a.ino
Using board 'avrda' from platform in folder: /home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8
Using core 'dxcore' from platform in folder: /home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8
Detecting libraries used...
/home/owner/.arduino15/packages/DxCore/tools/avr-gcc/7.3.0-atmel3.6.1-azduino4b/bin/avr-g++ -c -g -Os -Wall -std=c++17 -fpermissive -Wno-sized-deallocation -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -mrelax -w -x c++ -E -CC -mmcu=avr128da28 -DF_CPU=24000000L -DARDUINO=10813 -DARDUINO_avrda -DARDUINO_ARCH_MEGAAVR "-DDXCORE=\"1.3.8\"" -DDXCORE_MAJOR=1UL -DDXCORE_MINOR=3UL -DDXCORE_PATCH=8UL -DDXCORE_RELEASED=1 -I/home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/cores/dxcore/api/deprecated -I/home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/cores/dxcore -I/home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/variants/28pin-standard /tmp/arduino_build_380230/sketch/sketch_nov01a.ino.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
Error while detecting libraries included by /tmp/arduino_build_380230/sketch/sketch_nov01a.ino.cpp
Generating function prototypes...
/home/owner/.arduino15/packages/DxCore/tools/avr-gcc/7.3.0-atmel3.6.1-azduino4b/bin/avr-g++ -c -g -Os -Wall -std=c++17 -fpermissive -Wno-sized-deallocation -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -mrelax -w -x c++ -E -CC -mmcu=avr128da28 -DF_CPU=24000000L -DARDUINO=10813 -DARDUINO_avrda -DARDUINO_ARCH_MEGAAVR "-DDXCORE=\"1.3.8\"" -DDXCORE_MAJOR=1UL -DDXCORE_MINOR=3UL -DDXCORE_PATCH=8UL -DDXCORE_RELEASED=1 -I/home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/cores/dxcore/api/deprecated -I/home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/cores/dxcore -I/home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/variants/28pin-standard /tmp/arduino_build_380230/sketch/sketch_nov01a.ino.cpp -o /tmp/arduino_build_380230/preproc/ctags_target_for_gcc_minus_e.cpp -DARDUINO_LIB_DISCOVERY_PHASE
In file included from /home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/cores/dxcore/Arduino.h:26:0,
                 from /tmp/arduino_build_380230/sketch/sketch_nov01a.ino.cpp:1:
/home/owner/.arduino15/packages/DxCore/hardware/megaavr/1.3.8/cores/dxcore/core_devices.h:385:4: error: #error "Unrecognized combination of flash size and chip type"
   #error "Unrecognized combination of flash size and chip type"
    ^~~~~
exit status 1
Error compiling for board AVR DA-series (no bootloader).

**Comment by SpenceKonde** [comment]
Yiiiikes

THIS IS WHY WE DESPERATELTY NEED CI TESTING HEREEEEEE

**Comment by SpenceKonde** [comment]
Fix checked in.
