### ISSUE TITLE
Typo in boards.txt

### ISSUE THREAD

**Issue by sshwarts** [SpenceKonde/DxCore#172]
Spence:
In the 1.3.8 release, I think there's a typo in the boards.txt file:
avrdb.menu.appapm.full.build.appspmabr=.spmALL

appapm? Think it's supposed to be appspm ?
Causes Visual Code to say: Error: full: Invalid value for option "appapm" for board "avrdb"

**Comment by SpenceKonde** [comment]
Yup, that would be correct.
