### ISSUE TITLE
Error in parameter when burning bootloader

### ISSUE THREAD

**Issue by HenningSchou** [SpenceKonde/DxCore#185]
With an empty sketch, I select "Burn Bootloader" - which results in this error message:

> Error: cannot parse fuse, 'invalid literal for int() with base 0: '00100101''

The fuses are specified like this in the command line:

> --fuses 0:0x00 1:00100101 5:0b11000001 6:0b00001100 7:0x00 8:0x00 

If I copy the complete command to the Windows command prompt - and change "1:00100101" to "1:0b00100101" - it works as expected.

The issue was observed with Arduino 1.8.13 and DxCore version 1.3.6 - upgrading to 1.3.9 didn't change anything.
These are the settings (screen dump from Tools Menu):
![DxCoreToolsSettings](https://user-images.githubusercontent.com/94114837/141293302-c1edcc14-487b-46c0-8e4c-730c4a1fa9c2.png)

**Comment by SpenceKonde** [comment]
Holy shit. Yeah that is clear wrong, how did nobody notice

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***
