### ISSUE TITLE
Missing EEPROM library

### ISSUE THREAD

**Issue by obdevel** [SpenceKonde/DxCore#22]
Just tried compiling an existing project for DxCore and tripped over the missing EEPROM.h.

What's the status of this library ? Possible ? Coming ? Not happening ? 

Not the end of the world as my design has optional outboard I2C EEPROM, but support for the on-chip EEPROM would be nice.

I tried searching through the repo and google.

Thanks.

IDE 1.8.13, macOS 10.13.6, compiling for AVR128DA28 w/ Optiboot.

**Comment by SpenceKonde** [comment]
EEPROM.h will be added in a future release

**Comment by SpenceKonde** [comment]
hey, turns out the stock library works like a charm here...
