### ISSUE TITLE
SPI compilation errors (avrdx28 and avrdx32 targets)

### ISSUE THREAD

**Issue by obdevel** [SpenceKonde/DxCore#23]
`Compiling library "SPI"
/Users/xxx/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=avr128da28 -DF_CPU=24000000L -DARDUINO=10813 -DARDUINO_avrdx28 -DARDUINO_ARCH_MEGAAVR -DMILLIS_USE_TIMERB2 -DSIMPLE_ADC_WORKAROUND -I/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/cores/dxcore/api/deprecated -I/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/cores/dxcore -I/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/variants/28pin-standard -I/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/Wire/src -I/Users/xxx/Documents/Arduino/libraries/Streaming/src -I/Users/xxx/Documents/Arduino/libraries/Adafruit_MCP23017_Arduino_Library -I/Users/xxx/Documents/Arduino/libraries/AccelStepper/src -I/Users/xxx/Documents/Arduino/libraries/MCP3017AccelStepper -I/Users/xxx/Documents/Arduino/libraries/CBUS2515/src -I/Users/xxx/Documents/Arduino/libraries/CBUS/src -I/Users/xxx/Documents/Arduino/libraries/CBUSLED/src -I/Users/xxx/Documents/Arduino/libraries/CBUSSwitch/src -I/Users/xxx/Documents/Arduino/libraries/CBUSconfig/src -I/Users/xxx/Documents/Arduino/libraries/ACAN2515/src -I/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src -I/Users/xxx/Documents/Arduino/libraries/LedControl/src -I/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/EEPROM/src /Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp -o /var/folders/03/s3pv8qk91w78m4_st_nbxl5m0000gn/T/arduino_build_578598/libraries/SPI/SPI.cpp.o
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp: In member function 'bool SPIClass::pins(uint8_t, uint8_t, uint8_t, uint8_t)':
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:19: error: 'PIN_SPI_MOSI_PINSWAP_1' was not declared in this scope
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:19: note: suggested alternative: 'PIN_WIRE_SDA_PINSWAP_2'
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                   ^~~~~~~~~~~~~~~~~~~~~~
                   PIN_WIRE_SDA_PINSWAP_2
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:56: error: 'PIN_SPI_MISO_PINSWAP_1' was not declared in this scope
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                                                        ^~~~~~~~~~~~~~~~~~~~~~
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:56: note: suggested alternative: 'PIN_WIRE_SDA_PINSWAP_2'
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                                                        ^~~~~~~~~~~~~~~~~~~~~~
                                                        PIN_WIRE_SDA_PINSWAP_2
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:92: error: 'PIN_SPI_SCK_PINSWAP_1' was not declared in this scope
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                                                                                            ^~~~~~~~~~~~~~~~~~~~~
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:92: note: suggested alternative: 'PIN_WIRE_SCL_PINSWAP_2'
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                                                                                            ^~~~~~~~~~~~~~~~~~~~~
                                                                                            PIN_WIRE_SCL_PINSWAP_2
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:126: error: 'PIN_SPI_SS_PINSWAP_1' was not declared in this scope
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                                                                                                                              ^~~~~~~~~~~~~~~~~~~~
/Users/xxx/Library/Arduino15/packages/DxCore/hardware/megaavr/1.1.0/libraries/SPI/src/SPI.cpp:68:126: note: suggested alternative: 'PIN_WIRE_SDA_PINSWAP_2'
     if(pinMOSI == PIN_SPI_MOSI_PINSWAP_1 && pinMISO == PIN_SPI_MISO_PINSWAP_1 && pinSCK == PIN_SPI_SCK_PINSWAP_1 && pinSS == PIN_SPI_SS_PINSWAP_1)
                                                                                                                              ^~~~~~~~~~~~~~~~~~~~
                                                                                                                              PIN_WIRE_SDA_PINSWAP_2
`

Not urgent; just trying out an existing project.

IDE 1.8.13, macOS 10.13.6, compiling for AVR128DA28

Update : error occurs with avrdx28 and avrdx32 targets; avrdx48 and avrdx64 seem ok.

**Comment by SpenceKonde** [comment]
Thanks, this is sorted now.
