### ISSUE TITLE
Serial not working on CuriosityNano avr128db48 at least?

### ISSUE THREAD

**Issue by apws** [SpenceKonde/DxCore#232]
After testing the same sketch with 4 different boards - cnano avr 128db48 (DxCore), cnano tiny1627 (MTC), XMC2Go and Leonardo, it seems that Serial in DxCore does nothing - I have identified CDC pins also (here PB1,PB0) and flashed correct optiboot, but Serial monitor shows nothing in arduino ide, nor in vscode/arduino-ext. Initially I thought that something is very bad in vscode/arduino, so then I identified that my print(".") are not shown as NEVER flushed without any println() ... but thats really problem of theirs serial monitor.

I tried any combination of compilation/upload in arduino ide too, but serial simply doesnt sent nothing to monitor, or there is some weird behavior of settings (baud?) ... I dont know.

the sketch used is below
[main.txt](https://github.com/SpenceKonde/DxCore/files/7883785/main.txt)
//"programmer": "DxCore:nedbg"
//UART USB-CDC: PB1,PB0
//RESET: PF6

#define MY_LED PIN_PB3

// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(MY_LED, OUTPUT);
  Serial.begin(115200);
  delay(2000);
  Serial.println("BEGIN");
}

// the loop function runs over and over again forever
void loop() {
  Serial.println();
  Serial.print("Start");
  int i = 5;
  while(i>0)
  {
    i--;
    digitalWrite(MY_LED, HIGH);   // turn the LED on (HIGH is the voltage level)
    delay(450);                       // wait for a second
    digitalWrite(MY_LED, LOW);    // turn the LED off by making the voltage LOW
    delay(250);                       // wait for a second
    Serial.print(".");
    //Serial.flush();
  }
  Serial.print("End");
}
`

also below is .vscode/arduino.json used too
[arduino.txt](https://github.com/SpenceKonde/DxCore/files/7883799/arduino.txt)
`{
    "sketch": "main.ino",
    "board": "DxCore:megaavr:avrdbopti",
    "port": "COM17",
    "configuration": "chip=avr128db48,clock=24internal,bodvoltage=1v9,bodmode=disabled,resetpin=reset,millis=tcb2,printf=default,attach=allenabled,mvio=enabled,startuptime=8,wiremode=mors1,timeout=8sec,bootloaderusart=ser3",
    "programmer": "DxCore:nedbg",
    "output": "build"
}`

(vscode/arduino simply USES arduino ide tools, grabs  everything there and maps it to such settings and IDE UI, so its naturally bound to regular arduino ide setup, with all the boards, libs etc... )

**Comment by apws** [comment]
well, now I placed on breadboard plain avr128db28 and everything works with PA0,PA1 as UART
So something was weird only with CuriosityNano avr128db48 and his urt3 PB0, PB1 ??

**Comment by SpenceKonde** [comment]
I had the same problem with curiosity nano.... There;s something weird about the serial on those things, it's something with the USB interface they have... I dislike the boards enough that I haven't investigated further.
