### ISSUE TITLE
28-pin standard variant broken with double pin inclusion in digital_pin_to_port

### ISSUE THREAD

**Issue by nabelekt** [SpenceKonde/DxCore#237]
https://github.com/SpenceKonde/DxCore/blob/88d78df63bb2de8616aaf117188861b9fd846d15/megaavr/variants/28pin-standard/pins_arduino.h#L246-L249

Lines 248 and 249 here were introduced sometime between 3.1.10 and 4.1.6 and broke some stuff for me. Seems to me that PA0 and PA1 are accidently being included twice.

**Comment by nabelekt** [comment]
PR to resolve: https://github.com/SpenceKonde/DxCore/pull/238

**Comment by SpenceKonde** [comment]
Jesus christ.... how has this not been reported yet?!

**Comment by SpenceKonde** [comment]
THANK YOU!!!!!!!
