### ISSUE TITLE
jtag2updi compilation errors (any avrdx target)

### ISSUE THREAD

**Issue by Dlloydev** [SpenceKonde/DxCore#24]
When compiling the jtag2updi firmware, getting multiple warnings:
   _#warning "Part not supported - if you didn't provide all the needed pin definitions, that's why it's not compiling"_
Using DxCore 1.1.0-a with Windows 10 and Arduino 1.8.13

**Comment by SpenceKonde** [comment]
You must add the pin definitions to parts.h in order to add support for jtag2updi running on new hardware.
