### ISSUE TITLE
broken Images/Links

### ISSUE THREAD

**Issue by ProxyPlayerHD** [SpenceKonde/DxCore#25]
all imagines on this page are broken:
https://github.com/SpenceKonde/DxCore/blob/master/megaavr/extras/MakeUPDIProgrammer.md

and the link to the page "Making a cheap UPDI programmer" is broken on here:
https://github.com/SpenceKonde/DxCore/blob/master/Wiring.md

speaking of that page, it mentions the ATtiny a lot, even though it's for the AVR128Dx series? i assume it was just copy&pasted from another core.

**Comment by SpenceKonde** [comment]
Thanks, updated and fixed.

**Comment by ProxyPlayerHD** [comment]
the first one i mentioned is fixed, but the URL to the "Making a cheap UPDI programmer" page is still broken in the README.md file.

**Comment by SpenceKonde** [comment]
Looks fixed now. - not sure if I fixed after you mentioned that, or had fixed in local copy (as I just pushed update that included the readme)

**Comment by ProxyPlayerHD** [comment]
hmm strange, it's till broken for me.

I'm on the master branch on this page specifically: https://github.com/SpenceKonde/DxCore
