### ISSUE TITLE
SerialUPDI Lockbit Configuration

### ISSUE THREAD

**Issue by aliihsanhavan** [SpenceKonde/DxCore#270]
Hello,
I have a question regarding how to set the lock bits properly to lock program in AVR128DA48. Previously I was using jtag2UPDI configuration and I was able to achieve it by writing as "-Ulock:w:0x00:m"

Now with SerialUPDI, I couldn't find which fuses I need to overwrite for locking? Has anyone tried and successfully locked the program by using SerialUPDI interface? 

Can you please help me?

Kind regards.

**Comment by SpenceKonde** [comment]
I was just writingf to the author of that side of hte program (he wrapped the original so arduino could call it easily and he actually knows python, then I took a flamethrower to the low-level parts and made it run 20 times faster than it had been.
