### ISSUE TITLE
TCB2 disable and onboard ATSAMD21E18 Programmer use?

### ISSUE THREAD

**Issue by mikrocoder** [SpenceKonde/DxCore#29]
Hello,

I would like to ask why the timer TCB2 cannot be switched off? In the board selection menu this is provided, but it causes a compiler error. I want to configure all timers myself and I also need the TCB2 interrupt vector which remains blocked. Can you implement the millis/micros "disabled" internally real? So that no millis and no PWM is active by default.

I also want to ask if you can extend the controller package to flash the AVR128DB48 Curiosity Nano Board via USB?

MCUdude has this built into its MegaCoreX package. You select the Atmel nEDBG (ATSAMD21E18) on the board as programmer and can flash via USB as usual. Would that be possible? The SAMD21 is the same. https://github.com/MCUdude/MegaCoreX#curiosity-nano

Otherwise, best thanks for the controller package.

**Comment by SpenceKonde** [comment]
Support for the curiosity nano is far more complicated: https://github.com/SpenceKonde/DxCore/issues/5 In short, avrdude does not work with it, so it can't be supported as simply as you suggest. Note also that avrdude is not being maintained in any credible capacity anymore. That said, upcoming support for a new programming tool entirely may be in the offing, which would support this. More to come next week on that... it's gated by things that aren't in my control, but which seem to be prioritized highly by their authors. 

I fixed the disable millis issue last week, just realized I hadn't committed the change, it's now in github and will be in 1.2.1 release.
