### ISSUE TITLE
Error in http://drazzy.com/package_drazzy.com_index.json

### ISSUE THREAD

**Issue by khoih-prog** [SpenceKonde/DxCore#346]
The syntax error, recently introduced into `http://drazzy.com/package_drazzy.com_index.json`, line 3241, destroys the Board Support in Arduino IDE (v1.8.19) to `DxCore`, `ATtinyCore` and `megaTinyCore`

Original line 3241

```
            },
```

to be changed to

```
            }
```

---

Error when starting or opening `Board Support Package`

```
Skipping contributed index file /home/kh/.arduino15/package_drazzy.com_index.json, parsing error occured:
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character (']' (code 93)): expected a value
 at [Source: (FileInputStream); line: 3242, column: 12]
 at [Source: (FileInputStream); line: 3242, column: 11] (through reference chain: cc.arduino.contributions.packages.ContributionsIndex["packages"]->java.util.ArrayList[1]->cc.arduino.contributions.packages.ContributedPackage["tools"]->java.util.ArrayList[6]->cc.arduino.contributions.packages.ContributedTool["systems"])
```

**Comment by SpenceKonde** [comment]
That is the most pathetic excuse for a json parser I've ever worked with. Incredibly pedantic. Most json parsers will ignore the ,

**Comment by khoih-prog** [comment]
I understand the frustration. We have to live in the real world, with all `The Good, Bad and the Ugly`.

**Comment by khoih-prog** [comment]
BTW, is that better to put the `package_drazzy.com_index.json` inside `https://github.com/SpenceKonde/DxCore`, etc. ?

**Comment by SpenceKonde** [comment]
I'd forgotten that the json file was even available, with any changes, but it gets periodically autosynced by a cron job

**Comment by SpenceKonde** [comment]
Should be good now.

**Comment by khoih-prog** [comment]
Yes, OK now.
