### ISSUE TITLE
SerialUPDI has incorrect device ID for the AVR32DB48

### ISSUE THREAD

**Issue by mosqu-ito** [SpenceKonde/DxCore#351]
Sister Konde was angry with me and left me at the chalkboard to write this out...

<pre>
            Datasheet   UPDI Pies

 32DB48     0x1E9535    0x1E9532    <<=== *** Mismatch.
 32DB32     0x1E9536    0x1E9536
 32DB28     0x1E9537    0x1E9537

 64DB64     0x1E9616    0x1E9616
 64DB48     0x1E9617    0x1E9617
 64DB32     0x1E9618    0x1E9618
 64DB28     0x1E9619    0x1E9619

128DB64     0x1E970B    0x1E970B
128DB48     0x1E970C    0x1E970C
128DB32     0x1E970D    0x1E970D
128DB28     0x1E970E    0x1E970E
</pre>

I shall not neglect to report Device ID mismatches.
I shall not neglect to report Device ID mismatches.
I shall not neglect to report Device ID mismatches...

**Comment by SpenceKonde** [comment]
Thanks, by the way.
