### ISSUE TITLE
Serial wrong null terminator?

### ISSUE THREAD

**Issue by mikrocoder** [SpenceKonde/DxCore#362]
It has been taken care of. The problem was in the terminal setting NL as well as CR.

**Comment by SpenceKonde** [comment]
It's astounding that we managed to end up with two characters for newline... which are used in nearly every permutation by different devices. 

(as an aside, that has nothing to do with a null terminator - the null terminator is the 0x00 that marks the end of a string - there are only 255 characters that can be in a c string - a 0 instead marks the end of the string, which may be stored in a buffer larger than the string (sometimes much larger, so things like strlen checks the charaters, counting them as it does until it reaches a null (0) and that count up to there is what it returns. Nothing to do with the cr lf sequence that println() adds.)

**Comment by mikrocoder** [comment]
How Serial works is clear to me. The problem was solved shortly after the question was asked. I had different terminal settings in 2 open IDE and had not noticed it. That's why I wondered about different behavior. That was all. Had cost me 2 days of cause search.  :-)
