### ISSUE TITLE
USERSIG fails to write on AVR32DD14

### ISSUE THREAD

**Issue by KWolfe81** [SpenceKonde/DxCore#399]
Code below.  boot_cnt is always 4294967295 (-1) on reset.  EEPROM library working perfectly.

```
#include <USERSIG.h>
#include <EEPROM.h>

typedef struct
{
  uint32_t boot_cnt;
  uint32_t flashed_param_1;
  uint32_t flashed_param_2;
} flashed_config_t;

static flashed_config_t flashed_config = { 0 };

//----------------------------------------------------------------
void setup()
{ 
  Serial.pins(PIN_PA0, PIN_PA1);
  Serial.begin(115200);

  // wait until serial port opens for native USB devices
  while ( !Serial )
  {
    delay(1);
  }
  
  USERSIG.get( 0, flashed_config );

  Serial.println(flashed_config.boot_cnt);
  flashed_config.boot_cnt++;
  Serial.println(flashed_config.boot_cnt);

  USERSIG.erase();
  delay(100);
  
  USERSIG.put( 0, flashed_config );
  USERSIG.flush();
  delay(100);
```

**Comment by SpenceKonde** [comment]
well that's no good...

**Comment by SpenceKonde** [comment]
I'd love to test it but for some reason I don't understand, my AVR64DD14 test board is reporting that it's a different chip ID. It worked a few days ago....

**Comment by KWolfe81** [comment]
Huh.  I should be able to solder up an AVR64DD14 in the next day or two to
test.

**Comment by KWolfe81** [comment]
Same behavior on the AVR64DD14.  Further, maybe this should be another git issue, but EEPROM retention on arduino upload isn't working either (it's wiping the EEPROM):

![image](https://user-images.githubusercontent.com/15329313/219097752-7abf3515-f902-42d9-89bd-0773d80309dc.png)

**Comment by SpenceKonde** [comment]
Usersig library for Dx is setting the nvm command incorrectly, it's setting it to 1 (NOCMD) instead of 2 (Flash Write Enable)

**Comment by SpenceKonde** [comment]
Oh wait, that's not it, it's just doing the write process all wrong.

**Comment by KWolfe81** [comment]
Thanks for looking into that.  EDIT as well: ignore the comment above about the EEPROM getting wiped.  I didn't have the bootloader burned on that device.

**Comment by SpenceKonde** [comment]
Okay, I see why it's being set to 1, that's valid... but the indexes i'm writing sequentially are coming out wrong

Basically nothing looks like it should here.... I don't understand what's going on. 

I'm storing flags into the GPIOR's to export data from inside the library.... but the stuff that it reports makes no sense. 

And to add to the frustration, i fixed a bug that I was sure was the problem, but... it didn't fix it.

AAAh! Got it!

I was using the wrong kind of protected write - it needs a _PROTECTED_WRITE_SPM() not a normal _PROTECTED_WRITE

**Comment by KWolfe81** [comment]
@SpenceKonde It was a bit of a pain in the ass switching from Board Manager installed DxCore to manually installed core, but this fix works!  Thanks again.  You rock.
