### ISSUE TITLE
analogChannelToDigitalPin macro on ddseries has errant parenthesis

### ISSUE THREAD

**Issue by coburnw** [SpenceKonde/DxCore#403]
It seems that the forth conditional has an extra parenthesis which incorrectly groups the condition with the true expression:
https://github.com/SpenceKonde/DxCore/blob/6a4634510d24911ee11ed31bd79e3f67b79a96b8/megaavr/variants/32pin-ddseries/pins_arduino.h#L99

The same appears to be true for its compliment on line 103 also.  The db variants file compiles just fine.

Just as a fun aside, that very line causes my emacs to lock up when it attempts show brace completion...  Even after repair. 

Thanks for a great core!

**Comment by SpenceKonde** [comment]
Thanks you just barely squeaked into 1.5.5

**Comment by SpenceKonde** [comment]
Buddy those like 20 lines of bad code contained more buried treasure than captain blackbeard's lost hoard. 

Probably in all DD variants.

**Comment by SpenceKonde** [comment]
Actually not widespread in DD-series. Found some dubious but no syntactically invalid code in other DD variants.

**Comment by coburnw** [comment]
Kinda like buying a gold mine and only finding a couple nuggets near the entrance...
