### ISSUE TITLE
Upload error:"A programmer is required to upload" for AVR64DD32 on Arduino IDE 2.0.3

### ISSUE THREAD

**Issue by HonestQiao** [SpenceKonde/DxCore#419]
OS: macOS 11.7.4
Arduino IDE: 2.0.3
DxCore: 1.5.6
Board: AVR64DD32
<img width="964" alt="image" src="https://user-images.githubusercontent.com/696708/225981160-f18c8754-879f-46a8-aff4-345fba0eb189.png">

Problem:
When I upload a sketch , Arduino IDE throw an error:
A programmer is required to upload
<img width="529" alt="image" src="https://user-images.githubusercontent.com/696708/225981032-2625005c-8f4c-4351-a49b-def57e3982ea.png">

If I use Arduino IDE 1.8.19, everything is ok.

**Comment by pcfreak1201** [comment]
Well: 
[IDE 2.0.x is still unsupported](https://github.com/SpenceKonde/DxCore#ide-20x-unsupported-if-you-use-it-use-the-release-not-an-old-rc-all-versions-prior-to-200-rc92-known-to-have-critical-regressions)

**Comment by SpenceKonde** [comment]
Yeah I don't know what we're supposed to do in Arduino 2.x for parts that do not  have a n upload method except whatever the user has selected as the programmer.

**Comment by SpenceKonde** [comment]
Closing until there is an actionable change that I can make to resolve this issue.
