### ISSUE TITLE
Issue with pinout for TXD4 and RXD4 on AVR128Dx64

### ISSUE THREAD

**Issue by freaklabs** [SpenceKonde/DxCore#425]
Hi. Found a discrepancy in UART4 for the AVR128Dx64 chips. Here is the description from the image posted here:
![image](https://user-images.githubusercontent.com/1129352/232181221-02cdce42-0346-4698-aa77-98028a2981b7.png)
PE0 corresponds to RXD4
PE1 corresponds to TXD4

Here is the description from the datasheet:
![image](https://user-images.githubusercontent.com/1129352/232181265-e7137e70-7838-41a1-88c5-a62e7e465dea.png)
PE0 corresponds to TXD4
PE1 corresponds to RXD4

I haven't tested yet so I don't know if it's a datasheet error or an error in the image but it's probably best to give the datasheet the benefit of the doubt. That said, it wouldn't be the first time I've run into a datasheet error. 

Thought it'd be good to point the issue out.

**Comment by SpenceKonde** [comment]
Just an image error, I'll go fire up MS paint

**Comment by SpenceKonde** [comment]
Uhm that's not what I see on my copy in github,

**Comment by SpenceKonde** [comment]
Can you please link me to exactly where you're finding the bad file? I do not know where the file that needs to be fixed is.

**Comment by freaklabs** [comment]
It's the image on the Tindie site:
https://www.tindie.com/products/drazzy/avr128da-development-board-arduino-compatible/
Is there an image on github?
