### ISSUE TITLE
Syntax Errors in pinswap.h

### ISSUE THREAD

**Issue by CanHobby** [SpenceKonde/DxCore#427]
Seems that a lot of the #defines have termination semicolons..

for example I had to change line 366

from:  #define MOSI1  PIN_SPI1_MOSI;

to:     #define MOSI1  PIN_SPI1_MOSI  //  ;

to keep the Arduino IDE compiler happy...

wow - and I NEVER make mistakes.... ( and I have ocean front property in AZ )

**Comment by SpenceKonde** [comment]
I agree, that doesn't look right. Will see if it passes checkers with the changes.
