### ISSUE TITLE
AVR EA series support

### ISSUE THREAD

**Issue by mcuee** [SpenceKonde/DxCore#447]
Today I got the Microchip AVR64EA48 Curiosity Nano demo board and avrdude seems to work fine with the chip. It would be good for DxCore to support the EA series.

* https://github.com/avrdudes/avrdude/discussions/1257#discussioncomment-6203438

**Comment by SpenceKonde** [comment]
Yes that is planned forthe beta support inthe next release.

**Comment by SpenceKonde** [comment]
1.5.8 is out with the AVR-EB-series supported in some capacity. Please folks get outthere and try testingit and report problems!
