### ISSUE TITLE
Arduino IDE 2.x features like Suggestions and hover text stop working when using DxCore Boards

### ISSUE THREAD

**Issue by ProxyPlayerHD** [SpenceKonde/DxCore#471]
title says it.
for some reason none of those more advanced features of the IDE function correctly or at all when i have a Dx board selected.

for example, i'm using a circular buffer library which has tons of functions, when i type the name of one of my buffer variables followed by a dot i should be seeing suggestions for the different functions i can choose.

when the selected board is any of the DxCore ones it doesn't work and just shows random crossed out constants, variable, and keywords from my program:
![image](https://github.com/SpenceKonde/DxCore/assets/13576843/a9530ded-1dda-498b-9b41-ddb3e6e5b360)

but when i select any other board (built-in or not) like Arduino Mega, generic STM32F0, raspberry pi pico, etc. it works perfectly fine:
![image](https://github.com/SpenceKonde/DxCore/assets/13576843/803baa1c-fca2-4a48-b419-ff01742d482e)

same with the hover text (ie when you hover the cursor over a variable or function it shows you it's declaration, type, input parameters, etc.)

i thought these were universal IDE features regardless of the board selected... so why would this be happening?
or does each board need to implement or enable these features seperately?
either way i'm pretty confused

**Comment by SpenceKonde** [comment]
Beats me. Apparently yes they do need to be enabled by the core since it
doesn't work out of the box. I have not downloaded any 2.x.x versions and
do not know what is needed to fix this

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by SpenceKonde** [comment]
Please retest in latest version of the IDE once a latest version of the IDE is available which works (2.2.1 is no good) and reopen if this issue is still there.

**Comment by ProxyPlayerHD** [comment]
sorry for the late reply, i just tried it in 2.2.2 (nightly build 01.11.2023) and it still won't function. :(
