### ISSUE TITLE
Comparator Reference Voltages Incorrect?

### ISSUE THREAD

**Issue by simjman** [SpenceKonde/DxCore#488]
I was playing with the comparator reference voltages and couldn't work out why an interrupt wouldn't fire when using vref_2v500, but would when using vref_4v096. 

I believe the issue lies here:

https://github.com/SpenceKonde/DxCore/blob/2a5b6cc07cdd1c0bb7b11fa37b519c76378d1451/megaavr/libraries/Comparator/src/Comparator.h#L189

and here:

https://github.com/SpenceKonde/DxCore/blob/2a5b6cc07cdd1c0bb7b11fa37b519c76378d1451/megaavr/libraries/Comparator/src/Comparator.h#L191

This is from the DA/DB datasheet for reference:

![image](https://github.com/SpenceKonde/DxCore/assets/24268789/246e1e14-4dd3-448e-a6cf-3585540320f1)

**Comment by SpenceKonde** [comment]
Yup. I hadn't realized that they changed the order on the Dx/Ex series, I thought it was the same as tiny2 (mTC also gets the identical library). 

I belive it was like that since at least 1.3.0, maybe longer, Well over a year. You're the first to notice.

**Comment by SpenceKonde** [comment]
Fixed now

**Comment by simjman** [comment]
That's great, glad we caught it!
