### ISSUE TITLE
Board Manager SSH Certificate Expired

### ISSUE THREAD

**Issue by MiWeiss** [SpenceKonde/DxCore#520]
Following the instructions [here](https://github.com/SpenceKonde/DxCore/blob/master/Installation.md#boards-manager-installation-now-strongly-recommended-unless-helping-with-core-development), I am facing an error after step 1 as the network connection cannot be safely established.

![image](https://github.com/SpenceKonde/DxCore/assets/4815944/fe644326-85a4-45ba-b704-cc0d1d1b1784)

Manually checking, it indeed seems that the currently deployed certificate has expired.

**Comment by MiWeiss** [comment]
Note: As a short-term workaround, I prepared [https://github.com/SpenceKonde/DxCore/files/14349040/index-copy.json](https://github.com/SpenceKonde/DxCore/files/14349040/index-copy.json). This should not be used for long though, as it won't be updated

**Comment by andrewwootton** [comment]
I'm getting an "Error downloading" from the Arduino IDE with the additional boards manager set with http://drazzy.com/package_drazzy.com_index.json
Suspect its the same issue
