### ISSUE TITLE
Why would one turn off MVIO? (AVR DB)

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/DxCore#58]
It looks to me like turning off the MVIO fuse is something that nobody would ever want to do except maybe in production. 

If you're running from a single supply, you have all the power pins (including the VDDIO2 pin) tied to VDD anyway. So the only way you could even tell if it was enabled is by checking the fusebits. 

If you're running from dual supplies, on the other hand, disabling MVIO would be an HCF type situation, where the part would suffer immediate hardware failure as it tried to equalize the voltages on the two power supplies. Does anyone want to make the case for my not removing that bit from the configuration options and DxCore always running any chip that supports it with MVIO enabled?

**Comment by epccs** [comment]
Is it true that MVIO is enabled from the factory? I have not had a chance to verify that.

**Comment by SpenceKonde** [comment]
I'll double check on a virgin DB... but 99% sure it is. It would have to be, otherwise for dual supply systems. you couldn't program the chips in system - without tying the two rails together long enough to turn off MVIO...

**Comment by SpenceKonde** [comment]
1.3.x milestone - will remove MVIO from menu and always enable it in next version unless someone can convince me otherwise.

**Comment by Miraculix200** [comment]
MVIO was enabled on my virgin AVR128DB32s.

**Comment by SpenceKonde** [comment]
I've removed the menu option to disable MVIO. It does not appear to have a compelling use case. Let me know if anyone has a problem with that.
