### ISSUE TITLE
Bootloader file definitions missing for DB-series microcontrollers 

### ISSUE THREAD

**Issue by technoblogy** [SpenceKonde/DxCore#65]
Thanks for DxCore 1.3.0 - it's brilliant!

One point - when I first tried to burn a bootloader on an AVR128DB28 I got the message:

    avrdude: read from file '/Users/david/Library/Arduino15/packages/DxCore/hardware/megaavr/1.3.0/bootloaders/hex/{bootloader.file}_ser0.hex' failed
    Error while burning bootloader.

The explanation seems to be that the **bootloader.file** entries are missing from the **boards.txt** file in the **avrdbopti.menu.chip.** section.

When I added the line:

    avrdbopti.menu.chip.128DB28.bootloader.file=optiboot_dx128

in the appropriate section everything worked fine.

**Comment by SpenceKonde** [comment]
Thanks

**Comment by SpenceKonde** [comment]
Should be good in board manager version. Bunch of *other* stuff is hosed still, of course :-P
