### ISSUE TITLE
Upload to Curiosity Nano

### ISSUE THREAD

**Issue by sstaub** [SpenceKonde/DxCore#75]
The upload to the Curiosity Nano board work fine with Arduino IDE 1.8.13 on macOS Big Sur
but fails with the Arduino Pro IDE 0.13 nightly20210205
`Upload error: Error: 2 UNKNOWN: uploading error: uploading error: exit status 1`
 It seems that the Pro IDE doesn't know the programmer.

**Comment by SpenceKonde** [comment]
Sounds like a bug with the Pro IDE, why don't you report it to that development team?

**Comment by sstaub** [comment]
Ok, I will make an issue.

**Comment by sstaub** [comment]
Which version of avrdude did you use?
ProIDE says it is missing the programmer ID:
```
avrdude: Version 6.3-20201216
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is
"/Users/sstaub/Library/Arduino15/packages/DxCore/hardware/megaavr/1.3.0/avrdude.conf"
         User configuration file is "/Users/sstaub/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping


avrdude: Can't find programmer id "{upload.protocol}"
```

**Comment by sstaub** [comment]
I got a message from the Arduino PRO IDE team, you must use explicit "Upload Using Programmer" in the Sketch Menue. Sorry, I found this problem also using the Curiosity Nano 4809 board a while ago.

**Comment by per1234** [comment]
Yes, this is a bug in Arduino Pro IDE (https://github.com/arduino/arduino-pro-ide/issues/309), and not caused by anything wrong with DxCore.
