### ISSUE TITLE
README refers to in_p::link_output but it is in_p::link_out

### ISSUE THREAD

**Issue by baldengineer** [SpenceKonde/DxCore#89]
Minor documentation difference in [README.md](https://github.com/SpenceKonde/DxCore/blob/318f0534ab20606e5bdb1682f5ec5c9514527295/megaavr/libraries/Opamp/README.md). It refers to `in_p::link_output` to link Opamp1 and OpAmp2 to the previous Opamp's output. However, the code has the variable as `in_p::link_out`.

**Comment by SpenceKonde** [comment]
Thanks!
